name: My First Workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My First GitHub Actions Job"

      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: List Files
        run: |
          cd .github/workflows
          ls
        
      - name: Read file
        run: |
          cd .github/workflows
          cat workflow1.yaml
