name: Github Actions Core Concepts

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t dasaridevops/nginx-app:${GITHUB_SHA::7} .

      - name: Push the Docker image
        run: docker push dasaridevops/nginx-app:${GITHUB_SHA::7}

      - name: Run the docker image
        run: docker run -p 8089:80 dasaridevops/nginx-app:${GITHUB_SHA::7}

      - name: Wait for container
        run: sleep 5

      - name: Test application
        run: curl -I http://localhost:8089
