name: Github Actions Variables

on:
  workflow_dispatch

jobs:
  variables_job:
    runs-on: ubuntu-latest

    steps:
    - name: get the variable's values
      run: |
        echo "User Name: ${{ vars.USER_NAME }}"
        echo "Password: ${{ secrets.PASSWORD }}"
