name: Github Actions Variables

on:
  workflow_dispatch:

env:
  CITY: Guntur

jobs:
  variables_job:
    runs-on: ubuntu-latest

    steps:
      - name: Get the variable values
        run: |
          echo "User Name: ${{ vars.USER_NAME }}"
          echo "City: ${{ env.CITY }}"
          echo "Password is set: ${{ secrets.PASSWORD != '' }}"
